package mda.template.type;

import flca.mda.codegen.data.TemplateMergeStrategy;

public interface ICartridgeTemplateType {

	/**
	 * return the name to be used in the Tid enum definition. 
	 * Examples: ENTITY, SERVICE_MOCK etc
	 * @return
	 */
	String getEnumName();
	
	/**
	 * return the name of the jet-generated class
	 * @return
	 */
	String getTargetClassname();
	
	/**
	 * return the target package for the class generated by the jet-file
	 * @return
	 */
	String getTargetPackage();
	
	/**
	 * return the extension used targetfile, generated by the jetfile, for example ".java"
	 * @return
	 */
	String getTargetFileExtenstion();
	
	/**
	 * retur the target directory
	 * @return
	 */
	String getTargetDir();
	
	/**
	 * return the target packaged for jet-generated class
	 * @return
	 */
	String getJetPackage();

	/**
	 * return the target class for jet-generated class
	 * @return
	 */
	String getJetClassname();

	/**
	 * return the extension used for the jet file, for exammple: ".jet"
	 * @return
	 */
	String getJetExtension();
	
	/**
	 * return the rank
	 * @return
	 */
	int getRank();
	
	/**
	 * return trhe merge strategy
	 * @return
	 */
	TemplateMergeStrategy getMergeStrategy();
	
	/**
	 * return the classname(s), to which the generated template applies to 
	 * @return
	 */
	String getAppliesTo();
	
}
